### PR TITLE
Individual Project Proposal 

### PR DESCRIPTION
**Pull request by ducletan**
I was originally planning on completing a group proposal but was unsuccessful when it came to forming a group. I was then notified by an email that I was "emailed a solution" but seem to never receive any email of that sort. As a result, I panicked and created an individual proposal last minute for submission. I am so sorry if the quality of the work is not up to the expected standard, I tried my best :(

### CODE REVIEW

**Comment by ShanEllis** [comment]
Hey thanks for your note - since you wanted to do a group project, want to take a few more days to get this to the place where you want? I could extend the deadline until Wednesday for you. (Or, we can grade as is. Just let me know your preference.)

And, just to follow-up, I had sent an email with two other people...but then one of them said they found another group...so I think an individual project is best at this point. Let me know if that will work for you.

**Comment by ShanEllis** [comment]
small followup: just wanted to note that I have not read your proposal yet. (It could be very good!) I was just going off your message.

**Comment by ducletan** [comment]
Dear Professor Ellis,

Thank you for your concern and for being generous enough to offer me an extension. I think choosing the individual project option is best for me at this point. I will reach out to you and the TAs if I have any questions and issues. 

Best,
Duc

**Comment by ShanEllis** [comment]
Great - I'll merge your pull request here then to grade.

**Pull request merged**
